name: PoC CI

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r poc/sqlflow_source/python_impl/requirements.txt
      - name: Run unit tests
        run: |
          pytest -q poc/sqlflow_source/python_impl -q

  build-and-push:
    needs: python-tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Python PoC image
        uses: docker/build-push-action@v4
        with:
          context: poc/sqlflow_source/python_impl
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/langtian-nats-python-poc:latest
      - name: Save image name for deploy
        run: echo "IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/langtian-nats-python-poc:latest" >> $GITHUB_OUTPUT

  deploy-cloudbase:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: CloudBase deploy placeholder
        run: |
          echo "CloudBase deployment step requires repository secrets and CloudBase CLI or API."
          echo "See poc/deploy/README.md for manual steps and required secrets."
